type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run sql_table-input_filter_join_create-view"
      parameters:
        componentName: "Start"
    Run sql_table-input_filter_join_create-view:
      type: "run-transformation"
      parameters:
        componentName: "Run sql_table-input_filter_join_create-view"
        transformationJob: "sql_table-input_filter_join_create-view.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Run sql_table-input_filter_join_create-view:
      position:
        x: 120
        "y": 0
      tempMetlId: 2
