type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run Transformation"
      parameters:
        componentName: "Start"
    Run Transformation:
      type: "run-transformation"
      transitions:
        success:
        - "If"
      parameters:
        componentName: "Run Transformation"
        transformationJob: "table-input_pivot_unpivot_unite_transpose_create-table.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    If:
      type: "if"
      transitions:
        "true":
        - "Azure Blob Storage Load"
      parameters:
        componentName: "If"
        mode: "Simple"
        condition:
        - - "VAR_PROJECT_TEST1"
          - "Is"
          - "Less than"
          - "WQER"
        combineConditions: "And"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Azure Blob Storage Load:
      type: "azure-blob-storage-load"
      parameters:
        componentName: "Azure Blob Storage Load"
        stage: "[Custom]"
        authentication: "Credentials"
        azureStorageLocation: "azure://aakadlsgen2/aakroot/"
        pattern: ".*"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "ADDRESS"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter:
        fieldDelimiter:
        skipHeader:
        skipBlankLines: "False"
        dateFormat:
        timeFormat:
        timestampFormat:
        escape:
        escapeUnenclosedField:
        trimSpace: "False"
        fieldOptionallyEnclosed:
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType:
        onError: "Abort Statement"
        sizeLimitB:
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 10
        "y": 0
      tempMetlId: 1
    Run Transformation:
      position:
        x: 130
        "y": 0
      tempMetlId: 2
    If:
      position:
        x: 290
        "y": 0
      tempMetlId: 3
    Azure Blob Storage Load:
      position:
        x: 450
        "y": 20
      tempMetlId: 5
